[build]
  command = "npm install && npm run build"
  functions = "functions/"
[redirects]
  from = "/api"
  to = "/.netlify/functions/server"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}